### ISSUE TITLE
Expanded overview page does not remember if it was expanded or contracted

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3784]
The (+) next to the progress bar on the overview page can be expanded to show more details, such as the full list of failing checks or the status counts.

If you follow a failing check from this page and then return to the overview you will arrive with the overview contracted. This is confusing especially if you are stepping through types of failing checks from the overview.

**Comment by iafan** [comment]
Noticed this related discussion on IRC:

><phlax> dwaynebailey: im looking at #3784 - im wondering if i expand the checks on one page whether it should remain expanded on all pages, or whether it should only remain expanded on the page i clicked on?
<phlax> im assuming that it remembers per page
<dwaynebailey> phlax: I'd also assume as per page, though that's a lot of pages
<dwaynebailey> phlax: that main issue is to get away from it forgetting it was open.  So really its only a concern for the page from which we have come. Not any other pages.
<phlax> dwaynebailey: yep, it just means that if its stored on a cookie, the cookie has the potential to become larger if it has to remember more pages. I dont really imagine it would be a prob tho

I'd advise against remembering the state for every page out there. Extended stats can take the better half of the page, and having random pages to auto-open stats would become a frustrating experience.

Instead, I recommend adding `#details` hash to the URL when the overview pages are expanded and remove this hash when they are collapsed — this way, if one navigates from /some/browse/page/#details to some check, and goes through all the page, he will be redirected back to the same browsing page with expanded stats. Also, this allows to pass along the link with the forcibly opened extended stats.

cc @phlax

**Comment by phlax** [comment]
@iafan thanks for this.

I kinda realised using a cookie was bad so I implemented something similar to your suggestion, using checks=open as the hash param.

The only problem i encountered was that as the hash is not sent to the server, and therefore can't  be detected by get_previous_url(), i think it has to be included in the translation page url, eg:

http://localhost:8000/projects/tutorial/translate/#filter=untranslated&details=open

...and then added to the "go back to browsing" link.

**Comment by julen** [comment]
TBH I feel this is quite a hackish solution, and the code in the linked PR shows that.

I propose something simpler and cleaner:

* When the expanded stats are opened, we `pushState('', '', '?details')`. When they are closed, `?details` is removed.
* It's necessary to make sure this piece of state is taken into account on the initial page load.
* Whatever the current state of the expanded stats is, it's carried in the URL to the editor as part of the HTTP referrer. The editor already reads the referrer [when building the *previous URL*](https://github.com/translate/pootle/blob/9f476accb1bbbe9bbf36363fd1f6329ee184e746/pootle/core/url_helpers.py#L150-L177), so just make sure not to strip out this parameter.

No need to hack around the editor with ad-hoc bandages.

**Comment by dwaynebailey** [comment]
OK this is still broken.  @julen does your suggestion in https://github.com/translate/pootle/issues/3784#issuecomment-130586977 still apply after the substantial rewrite in this area?

**Comment by julen** [comment]
It's not broken, it hasn't been implemented (yet).
