### ISSUE TITLE
LibreOffice project - error opening the project after downloading and unzipping

### ISSUE THREAD

**Issue by valtermura** [translate/pootle#3852]
Hi

SO: Kubuntu / KDE 14.10 updated
Browser: Firefox 38.0

after having downloaded and unzipped the project with the command:

https://translations.documentfoundation.org/export/?path=/it/libo_help/

It is impossible to open the po files contained in it. The structure of the folders is correct, but I get this error in Kate:

![schermata1](https://cloud.githubusercontent.com/assets/10959279/8273086/79e35e50-185e-11e5-8bc4-177416480247.png)

Sorry for screenshot in Italian.

Moreover, Lokalize, my CAT tool, doesn't recognize the folders I put in the project, so I cannot see them. Also, it cannot open a po file due to an error contained in "row 3".

**Comment by jleclanche** [comment]
Is this `it-libo_help/it/libo_help/scalc.po`? I can open it just fine.

**Comment by valtermura** [comment]
If I download and open a single file, such as the one you indicate, I have no problems.
The problem starts when I download, unpack the zip file, and then try to open any po file contained in it.

**Comment by dwaynebailey** [comment]
@valtermura just downloaded this and viewed in vim, ran pocount, msgfmt.  No issue I can see on my side.

Can you maybe try open this in another localisation tool, poedit or another editor gedit or such.

And can you try tell us what the actual error message is.

As I said from side the zip if fine and the files within the zip are also fine.

**Comment by valtermura** [comment]
Which is the encoding of the files? Kate (the editor in KDE) tells me there's some problem with the encoding, it tries to open the file with UTF-8 encoding but it cannot succeed.
Could be an issue during the unzip operation?

**Comment by valtermura** [comment]
To be clear: if I download a single file, I have no problems at all. The problem happens when I download the zip file and then unpack it. So, obviously could be a problem from my side, too.

**Comment by jleclanche** [comment]
@valtermura this should be fixed, can you try?

**Comment by valtermura** [comment]
From my side, the problem still remains. Lokalize cannot open the files, due to an "error to line no. 3", and Kate editor opens the file in encoding UTF-8 but it contains invalid characters, so the file is unreadable.

Screenshots attached.

![schermata2](https://cloud.githubusercontent.com/assets/10959279/9288220/f20935d2-433b-11e5-97f4-53fd44c1b095.png)
![schermata3](https://cloud.githubusercontent.com/assets/10959279/9288222/f77d6178-433b-11e5-8de4-6945d2ccf3df.png)

**Comment by dwaynebailey** [comment]
LibreOffice extended timeouts on downloads.  This looks like a corrupt zip caused by timeouts mid download.

Using ``file some.zip`` would have helped to validate if the file was indeed corrupt.
