### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by akarienta** [translate/pootle#4092]
Hi, I have installed Pootle into new virtualenv and made `pootle init`, everything was ok. I didn't change the conf file. After command `pootle rqworker &` I have this error:

``` bash
(pootle)pootle@vm82:~$ pootle rqworker &
[1] 16142
(pootle)pootle@vm82:~$ 2015-09-22 15:22:28,675 INFO Loading custom settings from '/home/pootle/.pootle/pootle.conf'...
2015-09-22 15:22:29,008 INFO Using Python PO
Traceback (most recent call last):
  File "/home/pootle/.envs/pootle/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.7.1', 'console_scripts', 'pootle')()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 309, in main
    django_settings_module='pootle.settings')
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 289, in run_app
    management.execute_from_command_line(command)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/apps/accounts/models.py", line 38, in <module>
    from pootle_store.models import SuggestionStates, Unit
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 215, in <module>
    TMServer = SearchBroker()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/core/search/broker.py", line 36, in __init__
    self._servers[server] = getattr(module, _search_class)(server)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/core/search/backends/elasticsearch.py", line 26, in __init__
    self._create_index_if_missing()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/core/search/backends/elasticsearch.py", line 40, in _create_index_if_missing
    if self._server_setup_and_alive():
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/core/search/backends/elasticsearch.py", line 29, in _server_setup_and_alive
    return self._es is not None and self._es.ping()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 190, in ping
    self.transport.perform_request('HEAD', '/', params=params)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x3d66990>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x3d66990>: Failed to establish a new connection: [Errno 111] Connection refused)
```

I don't know what can be wrong. Any suggestions, please? 

``` bash
(pootle)pootle@vm82:~$ cat /etc/issue
Ubuntu 12.04.5 LTS \n \l
(pootle)pootle@vm82:~$ pootle --version
Pootle 2.7.1 (Django 1.7.10, Translate Toolkit 1.13.0-rc1)
(pootle)pootle@vm82:~$ python -V
Python 2.7.3
(pootle)pootle@vm82:~$ pip show pip
---
Metadata-Version: 1.1
Name: pip
Version: 7.1.2
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /home/pootle/.envs/pootle/lib/python2.7/site-packages
Requires:
Entry-points:
  [console_scripts]
  pip = pip:main
  pip2.7 = pip:main
  pip2 = pip:main
```

**Comment by phlax** [comment]
hi - i think there is a problem with the elasticsearch version

can you try doing
``
pip install elasticsearch==1.6.0
```

**Comment by Akarienta** [comment]
Thanks. I have en error during the elasticsearch installation:

``` bash
(pootle)pootle@vm82:~$ pip install elasticsearch==1.6.0
Collecting elasticsearch==1.6.0
/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading elasticsearch-1.6.0-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 490kB/s
Requirement already satisfied (use --upgrade to upgrade): urllib3<2.0,>=1.8 in ./.envs/pootle/lib/python2.7/site-packages/urllib3-1.12-py2.7.egg (from elasticsearch==1.6.0)
Installing collected packages: elasticsearch
  Found existing installation: elasticsearch 1.7.0
    Uninstalling elasticsearch-1.7.0:
      Successfully uninstalled elasticsearch-1.7.0
Successfully installed elasticsearch-1.6.0
```
and the another one on running rqworker again:

``` bash
(pootle)pootle@vm82:~$ pootle rqworker &
[1] 16787
(pootle)pootle@vm82:~$ Traceback (most recent call last):
  File "/home/pootle/.envs/pootle/bin/pootle", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: elasticsearch
```

**Comment by julen** [comment]
The latest error you're getting is related to pip — not much we can do besides telling you to try to find a workaround for the specific error (upgrade setuptools, re-install pootle, etc.) or even re-create the virtualenv.

**Comment by Akarienta** [comment]
Understand. I would post the solution here if I had found it.

**Comment by phlax** [comment]
@Akarienta we just released a version 2.7.2 - partly due to the issue with elasticsearch incompatibility.

Can you try upgrading to the latest version:
```
pip install --upgrade Pootle
```
hopefully that will sort things out

**Comment by Akarienta** [comment]
Thank you very much. Sad to say, the problem is still presented while installing pootle with `pip 7.1.2`. However I was able to install it correctly (and then run it) with very old `pip 1.1`. I'd suggest to make a note about this pip bug into doc because actualy there is written:

> Lastly, we want to make sure that we are using the latest version of pip:
```
(env) $ pip install --upgrade pip
```

**Comment by julen** [comment]
I just tried a fresh install in a clean environment, with an upgraded pip, and none of the issues described here can be reproduced. Could you double-check @Akarienta? It seems some weirdness has happened with your virtualenv+pip. Other than, as 2.7.2 pulls the `elasticsearch` version @phlax has commented, I wasn't able to reproduce the original issue being reported here.

**Comment by Akarienta** [comment]
@julen I have tried it many times. Maybe the problem is in virtualenv or virtualenvwrapper, I'll check it tomorrow.

```
$ apt-show-versions | grep virtualenv
python-virtualenv/precise uptodate 1.7.1.2-1
virtualenvwrapper/precise uptodate 2.11.1-2
```

**Comment by Akarienta** [comment]
Definitely, the bug is still presented. I have this error (command `pootle rqworker &` does the same thing):

``` bash
$ pootle --version
Traceback (most recent call last):
  File "/home/pootle/.envs/pootle/bin/pootle", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: rq>=0.5.0
```

With this configuration:

``` bash
$ cat /etc/issue
Ubuntu 12.04.5 LTS \n \l
$ pip --version
pip 7.1.2 from /home/pootle/.envs/pootle/local/lib/python2.7/site-packages (python 2.7)
$ python -V
Python 2.7.3
$ pip freeze | grep Pootle
Pootle==2.7.2
$ apt-show-versions | grep virtualenv
python-virtualenv/precise uptodate 1.7.1.2-1
virtualenvwrapper/precise uptodate 2.11.1-2
```

**Comment by julen** [comment]
I wonder why distribute is being used by latest pip there (which is an obsolete fork of setuptools). Does the same happen if you upgrade setuptools? What if you don't upgrade pip? (Not sure why that is suggested in the docs TBH, @phlax?).

**Comment by Akarienta** [comment]
@julen If I don't upgrade pip all is right. Which version should I update setuptools?

Btw, I have just tried to use elasticsearch as local TM and I got the very similar error to one which with I have opened this issue:

``` bash
$ pootle update_tmserver
2015-09-24 12:19:55,911 INFO Loading custom settings from '/home/pootle/.pootle/pootle.conf'...
2015-09-24 12:19:56,642 INFO Using Python PO
Traceback (most recent call last):
  File "/home/pootle/.envs/pootle/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.7.2', 'console_scripts', 'pootle')()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 309, in main
    django_settings_module='pootle.settings')
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 289, in run_app
    management.execute_from_command_line(command)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/update_tmserver.py", line 142, in handle
    es.indices.exists(self.INDEX_NAME)):
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 216, in exists
    self.transport.perform_request('HEAD', _make_path(index), params=params)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 85, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x1bcfd10>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x1bcfd10>: Failed to establish a new connection: [Errno 111] Connection refused)
```

**Comment by julen** [comment]
@Akarienta just try with `pip install --upgrade setuptools`

Re. the actual issue (finally!): is elasticsearch running at all? Also make sure the host where your elasticsearch server lives is not blocking connections on the port you have specified (default is 9200).

**Comment by Akarienta** [comment]
> Does the same happen if you upgrade setuptools?

The same bug here after setuptools update:

``` bash
$ pootle start
Traceback (most recent call last):
  File "/home/pootle/.envs/pootle/bin/pootle", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'translate-toolkit>=1.13.0' distribution was not found and is required by Pootle
```

**Comment by akarienta** [comment]
> Re. the actual issue (finally!): is elasticsearch running at all? Also make sure the host where your elasticsearch server lives is not blocking connections on the port you have specified (default is 9200). 

@julen I am sorry this was my fault. Elasticsearch didn't run properly because I overlooked in [the doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html) that Oracle JDK is needed instead of OpenJDK:

> The usual recommendation is to run the Oracle JDK with elasticsearch. However Ubuntu and Debian only ship the OpenJDK due to license issues. You can easily install the oracle installer package though. In case you are missing the add-apt-repository command under Debian GNU/Linux, make sure have at least Debian Wheezy and the package python-software-properties installed
``` bash
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java7-installer
java -version
```

There is a note about Java requirement in [Pootle doc](http://docs.translatehouse.org/projects/pootle/en/stable/features/translation_memory.html#translation-memory). Maybe specification about JDK dist and version will be useful or link on elasticsearch install doc at least?

**Comment by phlax** [comment]
@akarienta - can we close this bug now - or was there still an issue with the pip version?

**Comment by julen** [comment]
Thank you @akarienta, I have just added an explicit note in the docs along with the link you shared. Marking this as closed — the pip issue, if any, should be reported to them.

**Comment by unho** [comment]
Just for the record, I had just suffered the initial traceback on this issue (elasticsearch refused connection) and I have fixed it by manually creating the lockfile directory (/var/run/elasticsearch/) and assigning the right ownership and permissions, so when manually restarting elasticsearch the lockfile could be created.

**Comment by jamesone** [comment]
I didn't have Elasticsearch running when this error was occuring. Hope this helps!

**Comment by phlax** [comment]
hi @jamesone just to mention - you dont have to have Elasticsearch running for Pootle, but if its configured in your settings then it should be running
