### ISSUE TITLE
Elasticseach TM query gets 'string indices must be integers' exception

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4173]
This error occurs sporadically on ES queries.  Its pretty hard to replicate but in debugging with @phlax it seems like it could be a timeout issue.

`exceptions:TypeError: string indices must be integers`

```pytb
Traceback (most recent call last):
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.54.0.41/newrelic/api/web_transaction.py", line 711, in __iter__
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.54.0.41/newrelic/api/web_transaction.py", line 1087, in __call__
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.54.0.41/newrelic/hooks/framework_django.py", line 499, in wrapper
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_misc/util.py", line 59, in wrapper
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/decorators.py", line 66, in decorated_f
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/views.py", line 833, in get_edit_unit
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/models.py", line 912, in get_tm_suggestions
  File "/var/www/sites/mozilla/src/pootle/core/search/broker.py", line 51, in search
  File "/var/www/sites/mozilla/src/pootle/core/search/backends/elasticsearch.py", line 78, in search
```

**Comment by dwaynebailey** [comment]
Replicating the actual conditions seems very hard.  So I decided to replicate the error based on my own theory that the results where not as expected.

Using this code

```py
json_string_nores = """{
      "took" : 63,
      "timed_out" : false,
      "_shards" : {
              "total" : 5,
              "successful" : 5,
              "failed" : 0
      },
      "hits" : "Some string"
}"""

res = json.loads(json_string_nores)

if not isinstance(res['hits'], dict):
    print type(res['hits'])
else:
    for hit in res['hits']['hits']:
        print hit
```

You can get the same error.  Notes that usually ``'hits'`` is a list ``[]`` but here I make it a string.

I think the correct approach is to harden this code and highlight the content when this error occurs again.  Then at least we can handle the root cause of the error.

**Comment by julen** [comment]
We have also been randomly seeing this same exception.

Checking our Sentry's exception along with Elasticsearch-py's source code, this is definitely an error happening when making the [HTTP request to fetch the results](https://github.com/elastic/elasticsearch-py/blob/24b48852403ae3dd98b714f1914dd423c2c8ad68/elasticsearch/transport.py#L307). The actual request is [handled by default by urllib3](https://github.com/elastic/elasticsearch-py/blob/24b48852403ae3dd98b714f1914dd423c2c8ad68/elasticsearch/connection/http_urllib3.py), and the response data here is an empty string, which then propagates to the `'hits'` key from the `ElasticSearch.search()` results.

Since connection handlers (and their underlying libs) already log on failure and success, a proper way to further diagnose this would be to keep an eye on logging (both `elasticsearch` and `urllib3`) and pair the results whenever this exception happens again.

**Comment by phlax** [comment]
this was fixed in #4196

**Comment by unho** [comment]
This shouldn't be closed according to https://github.com/translate/pootle/pull/4196#issuecomment-158033445 but I can't find any reference to that discussion.

**Comment by julen** [comment]
This wasn't fixed as the comment at the time states, and the IRC discussion was from [November 17](https://botbot.me/freenode/pootle-dev/2015-11-17/?msg=54328113).
