### ISSUE TITLE
Caighdean Gaelic Machine Translation provider uses http only and breaks on https sites

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4600]
The Caighdean MT engine is hardcoded to use http.  This works on http Pootle sites.  But on on https sites.

Solutions:
1. Get Caighdean onto https - that will make it work for Pootle on https or http
2. Disable the checker if Pootle is running on http

**Comment by unho** [comment]
It seems we are waiting on a third party to implement an enhancement so we can adjust the MT feature to work with it, so unless we hear something soon I suggest to kick this to 2.8.1 milestone.

**Comment by kscanne** [comment]
API requests should now work over https.

**Comment by phlax** [comment]
great thanks @kscanne !

**Comment by unho** [comment]
Reopening since this is still not deployed and tested in MLO. And today we will have to wait until it finishes begin of translation cycle template updates.

**Comment by unho** [comment]
@kscanne Caighdean MT finally works on MLO. It is slow, but it works.

**Comment by kscanne** [comment]
Thanks everyone for your help with this!!  I tested and it works fine for me, and it will be a big help going forward.
