### ISSUE TITLE
Can't go past 18 incomplete units

### ISSUE THREAD

**Issue by julen** [translate/pootle#4625]
As already reported in #4560, when going through 18+ incomplete units, the editor gets stuck in the 18th unit, and it doesn't go further. Check the following recording as a reference:

![editor_bugs](https://cloud.githubusercontent.com/assets/16768/14281062/1de98824-fb37-11e5-9024-0af2be01442e.gif)

**Comment by phlax** [comment]
@julen im struggling to reproduce, can you provide me with a link

**Comment by julen** [comment]
This was a local test project. You can try importing any file with e.g. 25 untranslated units and translate.

**Comment by phlax** [comment]
@julen there was a problem with this in the first iteration, that was fixed at the time, there was also an issue of having get_unit_rows set - which is fixed in #4653.

Can you confirm that this is no longer an issue with the #4653 branch

**Comment by julen** [comment]
I definitely missed the last message through my notifications, apologies.

I can still reproduce the issue, and after some debugging this originates in the backend when [performing the search](https://github.com/translate/pootle/blob/fd10abf08121ef6c23373f67669956b8149bb63f/pootle/apps/pootle_store/unit/search.py#L154-L155):
```python
        if start > total:
            return total, total, total, self.results.none()
```

I'm testing now in a context where I go through 21 incomplete units, and after having translated some, in the request to check for new units (requested with `offset=20`) it returns there are still 8 left, but it doesn't fetch the remaining items (because `20 > 8`), the response being:

```json
{
    "unitGroups": [], 
    "start": 8, 
    "total": 8, 
    "end": 8
}
```

This also shows that `unitGroup` being empty here is the reason why the flashing popup appears (#4626).

**Comment by phlax** [comment]
hi @julen - the PR reffed above didnt include any changes to get_unit_rows, which i believe is the source of some of the problems you reported, but it looks like you may have found another.

**Comment by phlax** [comment]
@julen i believe this has been fixed as i havent managed to reproduce while debugging/testing the related bugs.

Im going to close this for now, but please reopen if the problem recurs

**Comment by ta2-1** [comment]
@phlax @unho I could reproduce a corner case for this issue:
- go https://mozilla.locamotion.org/bn_BD/ios/translate/firefox-ios.xliff#filter=suggestions
- pass through more than 18 units
- put zero here 
![image](https://cloud.githubusercontent.com/assets/682845/16306933/13d93fae-3968-11e6-8713-0aa0865e13a0.png)

- pass through units (18th will be the last)

**Comment by iafan** [comment]
Seems like this issue with "18 units at a time" wasn't fixed for good (see #4894).

**Comment by dwaynebailey** [comment]
@phlax basing my testing on @ta2-1 found failure I can replicate as follows:

* Go to a filter view e.g. https://mozilla.locamotion.org/af/firefox/translate/#filter=incomplete
* Manually change the start unit to anything withint the first offset range.  So 0-19
* Step through units.  You won't be able to step past unit 20.

So the issue seems to be that if you manually change the start position within the range of the first offset then we'll get stuck.  Its pretty consistently replicatable.  If you choose a number >=20 then everything works as we're then in the second offset and that seems to solve the problem.

**Comment by iafan** [comment]
Things are 3 times better now: I just stumbled upon the situation where I can't go past 54 units (18x3 magic number).

What I did is I filtered all units with critical errors in some project, was going through them one by one, ended up on the 54th unit (the pagination control says `54 / 282`), the URL is https://translate.evernote.com/projects/mac_v5_evernote/translate/#filter=checks&category=critical&unit=3791747&offset=36 and there are no more units below and Ctrl+Down doesn't work.

**Comment by dwaynebailey** [comment]
@iafan please post reproducable steps.  I don't get this at all on mlo with 117 critical units.  What I do get when using the keyboard is a pause when the current set is exhausted and we're waiting but the down arrow is reenabled when the set arrives.  If that is the issue then lets open a new bug for that please.

**Comment by iafan** [comment]
@dwaynebailey my understanding is that now this is not 100% reproducible. It went past two first 18-unit chunks just fine and choked on the third. It wasn't just a pause — units never came back. This may technically be something else (including a networking issue) and I'll keep an eye on this and provide additional information if I spot it. The reason I reopened this bug is that the end user experience is essentially the same — user can't go past a certain number of units. If my findings show that the nature of the issue is different, I'll open a new case and close this one.

**Comment by dwaynebailey** [comment]
@iafan the original bug reported here is reproduciable and fixed, I spent a considerable time trying to find the exact pattern to reproduce. And once I found the pattern it was very quick to get fixed. I did the same trying to replicate your bug, but I can't.  Clearly this is a new bug.  Opening a fixed bug to report an unreproducable issue that looks the same clouds the issue and doesn't allow anyone to track what has actually been fixed and what is new.  So when we talk of the 18 units fix do we mean the one that was fixed, or the one that you decided was the same as the one that was fixed but isn't?

Please just open a new bug :)  it means I have to type way less and its the right thing to do for reporting bugs.

**Comment by iafan** [comment]
Ok, I just got exactly the same problem again. And again on 54th unit.

The instructions are pretty much the same, though I didn't just go through the units by pressing Ctrl+Down, but also muted a check on each unit.

Here are the steps again:
1. I clicked on the red pill in the project browser to go through errors. The URL I clicked on was https://translate.evernote.com/projects/mac_v5_evernote/translate/#filter=checks&category=critical
2. Muted the check (clicked 'X' with the mouse), then pressed Ctrl+Down to go to the next unit. Repeated 54 times.
3. Pagination control says 54 / 194 and there are no more units loaded at the bottom.

Javascript console shows no errors. In on latest stable Windows / Chrome.

This is the log of XHR requests:
1. Right from the start: `https://translate.evernote.com/xhr/stats/checks/?path=%2Fprojects%2Fmac_v5_evernote%2F`
2. Immediately after (1st page of units): `https://translate.evernote.com/xhr/units/?path=%2Fprojects%2Fmac_v5_evernote%2F&category=critical&filter=checks`
3. alternating `edit/` and `toggle/` requests for 18 units
4. request for the second page of units: `https://translate.evernote.com/xhr/units/?path=%2Fprojects%2Fmac_v5_evernote%2F&category=critical&filter=checks&offset=18&previous_uids=3807041&previous_uids=4992561&previous_uids=3807045&previous_uids=4992562&previous_uids=3807047&previous_uids=3807048&previous_uids=4992563&previous_uids=3807050&previous_uids=3807051&previous_uids=4992564&previous_uids=3807053&previous_uids=3807054&previous_uids=4992565&previous_uids=3807056&previous_uids=3807057&previous_uids=3807058&previous_uids=3809590&previous_uids=4992593`
5. alternating `edit/` and `toggle/` requests for 18 units
6. request for the third page of units: `https://translate.evernote.com/xhr/units/?path=%2Fprojects%2Fmac_v5_evernote%2F&category=critical&filter=checks&offset=25&previous_uids=3809592&previous_uids=4992594&previous_uids=3809594&previous_uids=4992595&previous_uids=3809596&previous_uids=3809597&previous_uids=4992596&previous_uids=3809599&previous_uids=3809600&previous_uids=4992597&previous_uids=3809602&previous_uids=3809603&previous_uids=4992598&previous_uids=3809605&previous_uids=3809606&previous_uids=3809607&previous_uids=4992626&previous_uids=3812141`
7. alternating `edit/` and `toggle/` requests for 18 units

That's all. There's no request for new units past the third page.

I still have the browser page open in this state, so if you want me to run some debug JS, let me know.

**Comment by phlax** [comment]
@iafan i would defo like to track down the cause altho its getting a little late now. I would ask that you open a separate ticket tho - as the previous bug had a cause that was fixed. The problem may be related, but its pretty surely not the same, and would help in terms of triaging and cognition
